### ISSUE TITLE
new feature : Notifications

### ISSUE THREAD

**Issue by alejamp** [alejamp/lola-py-sdk#21]
La idea es :

se crean eventos de terceros que requieren llegar a el asistente, estos eventos serian por ejemplo : finalización del registro, inicio de compra ......

en Lola prompter se expondrá  un api que reciba estos eventos, donde le llegue en los parámetros el Lead

ejemplo del decorador para el SDK de python seria:

@lola.on_notification('notification_name')

**Comment by alejamp** [comment]
Lolapy SDK

```python
@lola.on_notification('testNotification')
def handle_new_conversation(session, ctx: LolaContext, msg):
    print(f'Got notification message: {msg}')
```

Prompter API Endpoint for notifications:

```
### Register Webhook

POST {{uri}}/api/notification/push
x-lola-auth: {{assistant_token}}
Content-Type: application/json

{
    "chatLead": {
        "botName": "finaconecta_demo_bot",
        "tenantId": "Ale2fMqvZCW7ZOWLom9S",
        "assistantId": "7o5XVecDMWZG5TMsfguLES",
        "channelSource": "telegram",
        "metadata": {},
        "signature": "1774478b2d1448d87a55a16c8766ba7377afc81600a6cfd42efcc33768b3a85f",
        "chatId": 1320141990
    },
    "label": "testNotification",
    "data": {
        "foo": "bar"
    }
}

```

**Comment by MatiusRock1** [comment]
@alejamp , donde encuentro el uri de los entornos que debo usar?

**Comment by MatiusRock1** [comment]
al revisar la implementacion, en el body la key no se llama data, se llama payload
